### PR TITLE
Add link to AH history

### PR DESCRIPTION
**Pull request by Ekwav**
Adds links to the AH history of players.

### CODE REVIEW

**Comment by metalcupcake5** [comment]
What is the purpose of this? We already have HyAuctions, and I dont think many people have heard of the site.

**Comment by Ekwav** [comment]
HyAuctions doesn't receive updates anymore.  
AH history has a longer history and also reveals unsold and thus active auctions.  
It can be used to see bids on active auctions and notify you when you are not in minecraft. (HyAuctions only displays ended auctions)
Also has a more intuitive way to search for items or players.
Easier to navigate as `Seller` and `Bidders` are clickable and don't have to be requested via a button.

**Comment by dukio** [comment]
@Ekwav you are the main developer right?

Changing/adding an auction history source can be done but I think we need to discuss it first.

Either way I can see there's a few issues.... like your about page links on privacy policy, terms and imprint links are all down...
The main website also seems to have some issues like `https://coflnet.com/images/portfolio/4.jpg`

Also the website seems to be rather new, judging by the discord size (<30 members)

**Comment by nstringham** [comment]
@Ekwav is there any chance that AH history will be made open source?

**Comment by Ekwav** [comment]
> @Ekwav is there any chance that AH history will be made open source?

It already is open source.
The current frontend is here:
https://github.com/matthias-luger/hypixel-react
And the backend is here:
https://github.com/Ekwav/HypixelSkyblock
Both repositories are likely to being moved to the Coflnet organization at some point.

@dukio 
I am considering myself to be the main dev yes. I will fix the issues with the main page this weekend. 
Thanks for pointing them out.
The backend actually predates HyAuctions as you can see in my commit history and by how far back the price data goes.

**Comment by nstringham** [comment]
Closing this because none of the maintainers showed interest in linking to AH history

**Comment by Ekwav** [comment]
@metalcupcake5 @dukio I would like to re-request this PR.
The discord grew to 4.5k members so far.
Hyauctions hasn't been updated for over a year now.
image

**Comment by nstringham** [comment]
Note: AH History is not open source

[Screenshot_20220619-125426_Chrome~2](https://coflnet.com/legal)

**Comment by Ekwav** [comment]
> Note: AH History is not open source
> 
> [Screenshot_20220619-125426_Chrome~2](https://coflnet.com/legal)

Counter note: That is the license for the website (mostly coflnet.com itself) all of the code powering sky.coflnet.com (AH history) is in fact open sourced and freely available on github under the AGPL (distributed over multiple Repositories viewable at https://github.com/Coflnet - did that after running into scaling issues with just one monolith) the setup instructions are here: https://github.com/Coflnet/hypixelskyblock#get-startedusage if you want to crosscheck that.

**Comment by nstringham** [comment]
> Counter note: That is the license for the website (mostly coflnet.com itself) all of the code powering sky.coflnet.com (AH history) is in fact open sourced and freely available on github under the AGPL (distributed over multiple Repositories viewable at https://github.com/Coflnet - did that after running into scaling issues with just one monolith) the setup instructions are here: https://github.com/Coflnet/hypixelskyblock#get-startedusage if you want to crosscheck that.

If that isn't AH History's license then why does AH History link to it?

I don't see this AGPL mentioned anywhere?

**Comment by Ekwav** [comment]
> > Counter note: That is the license for the website (mostly coflnet.com itself) all of the code powering sky.coflnet.com (AH history) is in fact open sourced and freely available on github under the AGPL (distributed over multiple Repositories viewable at https://github.com/Coflnet - did that after running into scaling issues with just one monolith) the setup instructions are here: https://github.com/Coflnet/hypixelskyblock#get-startedusage if you want to crosscheck that.
> 
> If that isn't AH History's license then why does AH History link to it?
> 
> I don't see this AGPL mentioned anywhere?

Its similar to how Google Chrome works, the product itself is licensed commercially but the underlying code (Chromium) is open source.
The website content can not be licensed under an OSS license because it contains images for which we don't have re-distribution rights (only usage).
Licenses of the underlying code:
https://github.com/Coflnet/HypixelSkyblock/blob/master/LICENSE
https://github.com/Coflnet/SkyApi/blob/master/LICENSE
https://github.com/Coflnet/SkyCommands/blob/master/LICENSE
https://github.com/Coflnet/SkyIndexer/blob/master/LICENSE
https://github.com/Coflnet/SkyCrafts/blob/master/LICENSE
https://github.com/Coflnet/kube/blob/main/LICENSE
[omitting a few repos but they (should) all have a (AGPL) LICENSE file]

**Comment by nstringham** [comment]
The react app doesn't have the license in it which is why I was confused.

Is it legal to make a closed source version of something that is licensed under GPL?

**Comment by Ekwav** [comment]
> The react app doesn't have the license in it which is why I was confused.
> 
> Is it legal to make a closed source version of something that is licensed under GPL?

Yeah, sorry about that, it apparently got lost while the react frontend was rebuilt to use next.js, I am working on getting that back (its one of the repos I am not the main developer for).

The AGPL requires you to release the source code of your modified app under the same license, if you make it accessible over the network.  
It differs from the GPL (without A) which only requires you to provide the source code if you distribute the binaries.  (see AGPL [clause 13](https://github.com/grafana/grafana/blob/main/LICENSE#L540)
Note that you do NOT need to release your code if you only call AGPL licensed program over the network (Ie. another microservice). 

Projects like grafana use the AGPL https://github.com/grafana/grafana/blob/main/LICENSE  
Mongodb used to use it as well but switched to the [SSPL](https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt) because of competition concerns. Its almost the same as AGPL but has a modified [clause 13](https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt#L478) that states you have to open source anything that you use to run it as a service for others (such as tools or frontends).

I like the AGPLv3 because it makes sure anyone can use my code for any reason but has to contribute improvements back if they want to profit off of it.  
https://sky.coflnet.com/api is our hosted instance of the system

**Comment by metalcupcake5** [comment]
@Ekwav As a team, we are in agreeance that SkyCofl provides a better auction and bazaar viewing experience than HyAuctions, but due to the specific monetization practices employed by SkyCofl, we have decided to not add a link to the website as we do not endorse those practices. Furthermore, after reviewing the monetization scheme of HyAuctions, we will also be removing the link to their site. We hope you understand our decision, and we welcome you to request this form of partnership again if SkyCofl is to ever change its practices.

**Comment by Ekwav** [comment]
> @Ekwav As a team, we are in agreeance that SkyCofl provides a better auction and bazaar viewing experience than HyAuctions, but due to the specific monetization practices employed by SkyCofl, we have decided to not add a link to the website as we do not endorse those practices. Furthermore, after reviewing the monetization scheme of HyAuctions, we will also be removing the link to their site. We hope you understand our decision, and we welcome you to request this form of partnership again if SkyCofl is to ever change its practices.

Thanks for getting back and providing an explanation. 
May I ask what monetization practices you would find acceptable?
Due to the storage costs of the replicated storage of the full ah and bazaar history as well as a mirror for tem (a project to index all items in the game) we can sadly not rely on only donations. But we currently would have enough server capacity to also host SkyCrypt. (In fact we do at https://skycrypt.coflnet.com )

**Pull request closed without merging**
