### PR TITLE
feat: add Crimson Isle Stats

### LINKED ISSUE #1463: API nether_island_player_data
image

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description 

Closes #1463

## Examples
image

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
## TO DO
- [x] ~~Update Skulls in constants (I don't have Kuudra or any nether related content unlocked on my profile so I can't do this ;-; and my guild is dead right now so I can't ask anyone to do it for me either)~~

image

**Review by dukio — CHANGES_REQUESTED** [review]
Errors out on these profiles:
- http://localhost:32464/stats/dynamicex
- http://localhost:32464/stats/20d6334b7f9541ebbf7f860205ebf846
Cannot read properties of undefined (reading 'kuudra_completed_tiers')

This profile doesn't even load, errors in EJS:
- http://localhost:32464/stats/aad581b2f90048a785a7573d31d7b862
image

**Comment by DuckySoLucky** [comment]
Solved

**Review by MartinNemi03 — APPROVED** [review]
lgtm, tested...

**Comment by MartinNemi03** [comment]
..but i'm not sure if it needs it's own category.
maybe we could merge all the different island stats under "Islands" category?

**Review by dukio — APPROVED** [review]
lgtm, tested

**Review by dukio — CHANGES_REQUESTED** [review]
See https://github.com/DuckySoLucky/SkyCrypt/pull/8

**Review by dukio — APPROVED** [review]
lgtm tested

**Pull request merged**
