### PR TITLE
Update Docker with a slimmer node image

### PR DESCRIPTION
**Pull request by WarpWing**

### CODE REVIEW

**Comment by nstringham** [comment]
What is slim?

**Comment by WarpWing** [comment]
@nstringham It's a slimmer version of the node.js image that only comes with the minimum packages to run. It's better than having a bloated image and our dependencies whereas this PR would implement the minimal packages with any extras being installed via npm after the slim image has been pulled. Should reduce image size.

**Review by MartinNemi03 — APPROVED** [review]
idk what this does, but lgtm

**Comment by WarpWing** [comment]
> idk what this does, but lgtm


Me when code

**Pull request merged**
