### PR TITLE
Recommend safari 15.4 (take 2)

### PR DESCRIPTION
**Pull request by nstringham**
this PR is the same as #1213 lets wait to merge it until we are ready to push code to users this time.

This PR recommends that iPhone users update to iOS 15.4 and Mac users update to macOS 12.3

before you merge this PR:
- [x] merge #1212
- [x] wait for iOS 15.4 to role out to the public
- [x] wait for macOS 12.3 to role out to the public

### CODE REVIEW

**Comment by MartinNemi03** [comment]
I'm once again sorry for this, let's wait this time.

**Comment by nstringham** [comment]
> I'm once again sorry for this, let's wait this time.

don't worry about it we are all learning

**Comment by nstringham** [comment]
It's been almost a month it might be time to consider merging this.

**Comment by dukio** [comment]
https://caniuse.com/usage-table

0.17% desktop
0.83% mobile

Still super early imo

**Comment by nstringham** [comment]
> https://caniuse.com/usage-table
> 
> 0.17% desktop 0.83% mobile
> 
> Still super early imo

I don't see a date. How old is that data? 

Also those percentages are of total internet users not of Safari users

**Comment by nstringham** [comment]
Oops wrong button

**Comment by dukio** [comment]
> > https://caniuse.com/usage-table
> > 
> > 0.17% desktop 0.83% mobile
> > 
> > Still super early imo
> 
> I don't see a date. How old is that data? 
> 
> Also those percentages are of total internet users not of Safari users

Can I use is pretty much always up to date... and yeah it's total, but a big chunk of safari users are still on the older version... idk maybe check again in a month?

**Comment by MartinNemi03** [comment]
> > > https://caniuse.com/usage-table
> > > 0.17% desktop 0.83% mobile
> > > Still super early imo
> > 
> > 
> > I don't see a date. How old is that data?
> > Also those percentages are of total internet users not of Safari users
> 
> Can I use is pretty much always up to date... and yeah it's total, but a big chunk of safari users are still on the older version... idk maybe check again in a month?

Now that majority of Safari users are on 15.4, could we perhaps go with this?

**Comment by nstringham** [comment]
> Now that majority of Safari users are on 15.4, could we perhaps go with this?

I think so. It's not like it will stop working for them it will just display a message

**Comment by dukio** [comment]
@MartinNemi03 yeah I think this can be merged

**Pull request merged**
