### PR TITLE
Recomend safari 15.4

### PR DESCRIPTION
**Pull request by nstringham**
This PR recommends that iPhone users update to iOS 15.4 and Mac users update to macOS 12.3

before you merge this PR:
- [x] merge #1212
- [ ] wait for iOS 15.4 to role out to the public
- [ ] wait for macOS 12.3 to role out to the public

### CODE REVIEW

**Comment by nstringham** [comment]
iOS 15.4 and macOS 12.3 released yesterday but we shou probably wait a bit to give people time to update before we start showing the popup

**Comment by MartinNemi03** [comment]
> iOS 15.4 and macOS 12.3 released yesterday but we shou probably wait a bit to give people time to update before we start showing the popup

I suppose we can wait with pulling this into production then.

**Review by MartinNemi03 — APPROVED** [review]

**Comment by dukio** [comment]
@MartinNemi03 if you merge this into development we can't wait to merge it into production though... cause development will be production soon, no?

**Comment by MartinNemi03** [comment]
> @MartinNemi03 if you merge this into development we can't wait to merge it into production though... cause development will be production soon, no?

Depends on who'll merge development into production. That's still a manual process.

**Comment by dukio** [comment]
> > @MartinNemi03 if you merge this into development we can't wait to merge it into production though... cause development will be production soon, no?
> 
> Depends on who'll merge development into production. That's still a manual process.

Yeah but... we can't do that before a couple months I would say, at least... and we can't wait that much before pushing any update to SkyCrypt

**Pull request merged**
