### PR TITLE
refactor: Split `stats.ejs` to multiple EJS files

### LINKED ISSUE #1737: Refactor: Split stats.ejs into multiple section files
I feel like with the way we're currently going, the main stats.ejs file is slowly becoming unmaintainable. 

I would suggest splitting the EJS file into seperate files based on the sections (Armor, Pets etc.) and do that over a certain span until we're done with the splitting and all PRs are on the new splitted files.

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

> Currently there's bug, importing `itemIcon()` from `stats.ejs` doesn't seem to work for some reason. I found fix by copy pasting `itemIcon()` function to every file which uses it

Closes #1737

This is completed version of [ejs-sections](https://github.com/SkyCryptWebsite/SkyCrypt/tree/ejs-sections) by @MartinNemi03

### CODE REVIEW

**Comment by MartinNemi03** [comment]
Currently waiting for finalization of how we should proceed with this and unit tests for compilation of different section files

**Review by WarpWing — APPROVED** [review]
Looks good to me. We should really merge this ASAP for easier maintainability. I can start going over it with comments.

**Comment by DuckySoLucky** [comment]
> Looks good to me. We should really merge this ASAP for easier maintainability. I can start going over it with comments.

Outdated atm

**Comment by WarpWing** [comment]
> > Looks good to me. We should really merge this ASAP for easier maintainability. I can start going over it with comments.
> 
> Outdated atm

Ur mom is outdated

**Comment by DuckySoLucky** [comment]
Too many  conflicts & we won't do it all at once

**Pull request closed without merging**
