### PR TITLE
Scatha Pet

### LINKED ISSUE #625: Add Scatha pet
player that has it [TheBestPie](https://sky.shiiyu.moe/stats/TheBestPie/Peach#Pets)

### PR DESCRIPTION
**Pull request by dukio**
Fixes #625 

https://sky.shiiyu.moe/stats/TheBestPie/Peach

image image

image

### CODE REVIEW

**Comment by dukio** [comment]
Updated the stats after the legendary screenshot, but no way to test it unfortunately :( (no player has it in inventory)

**Comment by metalcupcake5** [comment]
just buy it from ah smh

**Comment by dukio** [comment]
image

**Comment by dukio** [comment]
image

**Pull request merged**
