### PR TITLE
Updating explanations on how to correctly obtain API keys

### PR DESCRIPTION
**Pull request by DespicableGoose**
The method of obtaining Hypixel API keys was recently changed, along with this announcement on the Hypixel forums: https://hypixel.net/threads/hypixel-developer-dashboard-public-api-changes-june-2023.5364455/

### CODE REVIEW

**Review by DuckySoLucky — APPROVED** [review]
lgtm

**Review by metalcupcake5 — APPROVED** [review]

**Comment by metalcupcake5** [comment]
@TheTrueShaman pls fix prettier errors ty

**Comment by DespicableGoose** [comment]
@metalcupcake5 It should hopefully work now!

**Comment by DespicableGoose** [comment]
@metalcupcake5 I'm sorry about that last one, but it should definitely work this time, 100%.

**Review by WarpWing — APPROVED** [review]
Solid stuff! Thanks for contributing!

**Comment by metalcupcake5** [comment]
aint no way it failed again

**Pull request merged**
