### PR TITLE
remove slayer drops

### PR DESCRIPTION
**Pull request by nstringham**
This PR does 3 things:
- remove average drops
- refactor slayer styles (using the grid for kills)
- remove unused constants from `stats.ejs`
## Before:
image
## After:
image

### CODE REVIEW

**Review by dukio — APPROVED** [review]

**Review by MartinNemi03 — APPROVED** [review]

**Comment by FantasmicGalaxy** [comment]
Looks a little funky with the stuff being aligned towards the left, but not sure how you could make that better. Maybe only 3 columns so that the second row doesn't feel as empty?

**Comment by FantasmicGalaxy** [comment]
Or maybe remove the total and center the t5 for revs?

**Comment by dukio** [comment]
> Looks a little funky with the stuff being aligned towards the left, but not sure how you could make that better. Maybe only 3 columns so that the second row doesn't feel as empty?

My proposal was this but it was rejected
image

**Comment by FantasmicGalaxy** [comment]
Huh. I like that better but it does still look kinda empty

**Comment by MartinNemi03** [comment]
I agree that I like dukio's proposal. At least the centering of the elements.

**Comment by nstringham** [comment]
I think centering looks really weird when it has an even number in the top row and an odd in the button

**Comment by dukio** [comment]
so... what do we do?

**Comment by MartinNemi03** [comment]
> so... what do we do?

I suggest merging it into master and if any further changes are approved, we can always open a new PR.

**Review by FantasmicGalaxy — APPROVED** [review]

**Comment by dukio** [comment]
> > so... what do we do?
> 
> I suggest merging it into master and if any further changes are approved, we can always open a new PR.

Approve 👍

**Pull request merged**
