### PR TITLE
Update CI/CD yml badge

### PR DESCRIPTION
**Pull request by WarpWing**
Updated CI/CD yml badge

### CODE REVIEW

**Comment by WarpWing** [comment]
Also updated my theme for fun

**Comment by soopyc** [comment]
what the scallop warp active1!???!?!?!!??!

LGTM.

**Review by soopyc — APPROVED** [review]

**Comment by WarpWing** [comment]
> what the scallop warp active1!???!?!?!!??!
> 
> LGTM.

Yearly contribution to frontend (ain't no way skycrypt getting unit testing before gta 6)

**Review by metalcupcake5 — APPROVED** [review]
your're are mother

**Pull request merged**
