### PR TITLE
unfavorite

### PR DESCRIPTION
**Pull request by nstringham**
adds the ability to remove favorites

### CODE REVIEW

**Review by MartinNemi03 — APPROVED** [review]
Looks good, I'll keep to Metal if he wants to merge this, but it looks good.

**Comment by metalcupcake5** [comment]
uh i've already made a system for this in my local files

**Comment by metalcupcake5** [comment]
i'll compare the two, yours may be better

**Comment by nstringham** [comment]
Um, I haven't finished properly merging this with 004b5595fb158f61af1a23371190ad40994d96f3 can you please undo the merge and reopen the PR until I'm done with that.
Sorry there's not discussing of that here; me and metal will talking on discord in #nerds
I should be ready some time this weekend and I'll make a comment here when I am

**Comment by MartinNemi03** [comment]
> 
> 
> Um, I haven't finished properly merging this with [004b559](https://github.com/SkyCryptWebsite/SkyCrypt/commit/004b5595fb158f61af1a23371190ad40994d96f3) can you please undo the merge and reopen the PR until I'm done with that.
> Sorry there's not discussing of that here; me and metal will talking on discord in #nerds
> I should be ready some time this weekend and I'll make a comment here when I am

Yeah, sorry for that once again..

**Pull request merged**
