### PR TITLE
added a theme based on the default ubuntu 16.10 wallpaper

### PR DESCRIPTION
**Pull request by doej1367**
adds the theme 'SkyCrypt OS'

NOTE: due to how themes request recources from the server this could only be tested so far.
Also this is a graphical addition and may look different than how it looked to me on my screen.
A second opinion is needed!

NOTE 2: the ubuntu wallpapers are normally under the creative comon licence, 
but i couldn't find any reference if this one is as well...

Here some examples how this theme looks like:
grafik
grafik

### CODE REVIEW

**Comment by nstringham** [comment]
All of the themes so far have had a screenshot from hypixel skyblock as the background so this feels kinda out of place.

Additionally this theme's color is very similar to Sunrise Orange.

**Comment by doej1367** [comment]
> All of the themes so far have had a screenshot from hypixel skyblock as the background so this feels kinda out of place.
> Additionally this theme's color is very similar to Sunrise Orange.

It is supposed to be very different and out of place, because it is the "skycrypt os" joke made real for the 100th pr. Some nerds and me talked about it in the #nerds channel and the goal is to make it as if it was an operating system and not a website. And yes I know the colors are similar to sunrise, but thats just an coincidence (its based on the ubuntu orange). I dont really expect this to be implemented anytime soon, but - who knows - maybe one day... at least its done already and just waits to be merged.

**Comment by WarpWing** [comment]
This is insane. I would personally use this. +1 from me

**Comment by Pottedplant530** [comment]
@MartinNemi03 I'd close this one,

**Comment by MartinNemi03** [comment]
> 
> 
> @MartinNemi03 I'd close this one, for risk of copyright

I think I'll leave this for @Shiiyu to judge.

**Comment by Pottedplant530** [comment]
Alrightie

**Comment by WarpWing** [comment]
> @MartinNemi03 I'd close this one, for risk of copyright

What copyright? They can't own a colorscheme xd.

**Comment by doej1367** [comment]
> What copyright? They can't own a colorscheme xd.

There was that one man...
https://www.quora.com/What-are-all-the-artworks-and-artists-referred-to-or-pictured-as-part-of-Tony-Starks-art-collection-in-the-Iron-Man-film-series

**Comment by Pottedplant530** [comment]
> > @MartinNemi03 I'd close this one, for risk of copyright
> 
> What copyright? They can't own a colorscheme xd.

I meant the backgroud but idk

**Comment by Pottedplant530** [comment]
martin being pinged in a reply

**Comment by doej1367** [comment]
> I meant the backgroud but idk

I think he ment that as well describing it as just a 'colorscheme'

**Comment by SkyCryptUser** [comment]
ur mom stale

**Comment by WarpWing** [comment]
One day, someone will merge this.

**Comment by WarpWing** [comment]
Also, this is the 100th pull request. Pogs :D

**Comment by nstringham** [comment]
> One day, someone will merge this.

I hope not

**Comment by WarpWing** [comment]
Truly an end to such a era. RIP #100

**Pull request closed without merging**
