### PR TITLE
Node v16

### PR DESCRIPTION
**Pull request by nstringham**
**ACTION REQUIRED**: when this PR is merged the server **MUST** be updated to node 16

This PR updates to node v16 (and npm v7)

it also uses some new JS features in node 16 to improve readablity

### CODE REVIEW

**Review by dukio — APPROVED** [review]
lgtm, tested

**Comment by dukio** [comment]
Running `npm ci` with npm 8.x (I have 8.3.0, latest) it reports some vulnerabilities (1 moderate, 4 high):

```cmd
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/cliui/node_modules/ansi-regex
node_modules/eslint/node_modules/ansi-regex
node_modules/table/node_modules/ansi-regex
node_modules/wrap-ansi/node_modules/ansi-regex
node_modules/yargs/node_modules/ansi-regex

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install ts-lit-plugin@1.0.5, which is a breaking change
node_modules/lit-analyzer/node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/lit-analyzer/node_modules/fast-glob
    lit-analyzer  >=0.0.7
    Depends on vulnerable versions of fast-glob
    node_modules/lit-analyzer
      ts-lit-plugin  >=1.0.6
      Depends on vulnerable versions of lit-analyzer
      node_modules/ts-lit-plugin

5 vulnerabilities (1 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Should we look into this or just ignore it for now?

**Comment by MartinNemi03** [comment]
> Running `npm ci` with npm 8.x (I have 8.3.0, latest) it reports some vulnerabilities (1 moderate, 4 high):
> 
> ```batchfile
> # npm audit report
> 
> ansi-regex  >2.1.1 <5.0.1
> Severity: moderate
>  Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
> fix available via `npm audit fix`
> node_modules/cliui/node_modules/ansi-regex
> node_modules/eslint/node_modules/ansi-regex
> node_modules/table/node_modules/ansi-regex
> node_modules/wrap-ansi/node_modules/ansi-regex
> node_modules/yargs/node_modules/ansi-regex
> 
> glob-parent  <5.1.2
> Severity: high
> Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
> fix available via `npm audit fix --force`
> Will install ts-lit-plugin@1.0.5, which is a breaking change
> node_modules/lit-analyzer/node_modules/glob-parent
>   fast-glob  <=2.2.7
>   Depends on vulnerable versions of glob-parent
>   node_modules/lit-analyzer/node_modules/fast-glob
>     lit-analyzer  >=0.0.7
>     Depends on vulnerable versions of fast-glob
>     node_modules/lit-analyzer
>       ts-lit-plugin  >=1.0.6
>       Depends on vulnerable versions of lit-analyzer
>       node_modules/ts-lit-plugin
> 
> 5 vulnerabilities (1 moderate, 4 high)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> ```
> 
> Should we look into this or just ignore it for now?

Maybe we could just test if fixing it doesn't break anything.

**Comment by dukio** [comment]
> Maybe we could just test if fixing it doesn't break anything.

If you mean the `npm audit fix --force` doesn't work or doesn't fix much, maybe only 1 error/warning... problem is mostly it seems to be stuff that is a dependency of a dependency of something we need... so if they didn't update yet I don't think we can do much (but I don't have much experience with these things so I'm not sure)

**Comment by nstringham** [comment]
I fixed a vulnerability with `ansi-regex` by performing an update

the only other vulnerability reported by `npm audit` is a vulnerability with `glob-parent` which is required by `lit-analyzer` (see https://github.com/runem/lit-analyzer/issues/213) however, because this is a denial of service vulnerability and `lit-analyzer` only runs at compile time and during development this vulnerability doesn't actually effect us

**Review by dukio — APPROVED** [review]
lgtm didn't test

**Pull request merged**
