### PR TITLE
Docs improve README.md

### PR DESCRIPTION
**Pull request by Kartik192192**

### CODE REVIEW

**Comment by WarpWing** [comment]
So what does this improve?

**Comment by metalcupcake5** [comment]
and why do we need to add this?

**Comment by Kartik192192** [comment]
just for swag t shirts from hackstars

I think you can understand bro.
Please don't mind...😀😀🤗🤗

**Comment by Kartik192192** [comment]
I'm just a beginner coder. So I actually don't know what to do...

**Comment by metalcupcake5** [comment]
https://hacktoberfest.digitalocean.com/details#quality

**Pull request closed without merging**
