### PR TITLE
Docker compose stack

### PR DESCRIPTION
**Pull request by hannesfant**
Simple stack to improve devex by running redis & mongo in containers instead of having to keep them as local programs
Wasn't sure if the already existent dockerfile for the actual website is up to date or not, so didn't add it to the stack

### CODE REVIEW

**Comment by hannesfant** [comment]
Made some buttons feel more clickable as well to improve the general UX of them

**Comment by metalcupcake5** [comment]
could you make that a separate pr

**Comment by hannesfant** [comment]
Yeah they were supposed to be 2 different ones but got merged for some reason. Can't figure out how to split it in the web ui, and the second one only has like 2 line changes that don't interfere with anything else so I don't think it's the end of the world to keep them in one PR in this case

**Comment by metalcupcake5** [comment]
the reason i would prefer a separate pr is, while i approve of the other changes, i dont have enough experience with docker to accept it and dont want to merge something that hasn't been reviewed

**Comment by hannesfant** [comment]
Totally understandable, however this compose stack is so simple that realistically it shouldn't affect anything. It's right out of one of my other dev environments that have worked fine for about a year at this point. Also, it's just part of the dev environment and not production, so using it is completely optional, and it doesn't break anything, just improves the general dev experience :)

**Review by WarpWing — APPROVED** [review]
LGTM! Note to all (Not including OP and me) that this is for dev envs only. This is not for a production stack though it is something you could do.

**Comment by WarpWing** [comment]
Hey @hannesfant ! My name is WarpWing. I'm SkyCrypt's DevOps Consultant and the closest thing SkyCrypt has to a "Docker Expert" that metalcupcake5 was talking about. I just want to say thanks for the PR! I think we could definitely build on this especially since SkyCrypt is looking to migrate from pm2 to Docker so this would provide a good start for strictly dev envs. Definitely has my stamp of approval!

**Comment by hannesfant** [comment]
> Hey @hannesfant ! My name is WarpWing. I'm SkyCrypt's DevOps Consultant and the closest thing SkyCrypt has to a "Docker Expert" that metalcupcake5 was talking about. I just want to say thanks for the PR! I think we could definitely build on this especially since SkyCrypt is looking to migrate from pm2 to Docker so this would provide a good start for strictly dev envs. Definitely has my stamp of approval!

Awesome. Is the current dockerfile good to use for development purposes or is it still being worked on?

Also, @metalcupcake5 feel free to merge the PR once you have time, looks like it's ready :)

**Comment by hannesfant** [comment]
> could you make that a separate pr

Managed to get this done :) #1740

**Comment by WarpWing** [comment]
> > Hey @hannesfant ! My name is WarpWing. I'm SkyCrypt's DevOps Consultant and the closest thing SkyCrypt has to a "Docker Expert" that metalcupcake5 was talking about. I just want to say thanks for the PR! I think we could definitely build on this especially since SkyCrypt is looking to migrate from pm2 to Docker so this would provide a good start for strictly dev envs. Definitely has my stamp of approval!
> 
> Awesome. Is the current dockerfile good to use for development purposes or is it still being worked on?
> 
> Also, @metalcupcake5 feel free to merge the PR once you have time, looks like it's ready :)

Yes, the current dockerfile should be good for development purposes. That's just the dockerfile on it's own. We have yet to do some work with volumes among other things. It is still being worked on so it may not work out of the box. Please let me know if you have any more questions.

**Review by WarpWing — APPROVED** [review]
Looks good to me! I know this docker-compose file is for dev envs only but I think it would be an interesting idea to include nginx+letsencrypt into another compose stack designed for small-time prod deployments. Maybe we could even consider dockerizing skycrypt itself. Would be interesting to see how a docker skycrypt deployment could scale at large.

**Comment by MartinNemi03** [comment]
> Looks good to me! I know this docker-compose file is for dev envs only but I think it would be an interesting idea to include nginx+letsencrypt into another compose stack designed for small-time prod deployments. Maybe we could even consider dockerizing skycrypt itself. Would be interesting to see how a docker skycrypt deployment could scale at large.

That sounds like an interesting idea into the future, but I think there are a lot of things to be redone before we'll be even able to do that.

**Comment by MartinNemi03** [comment]
@hannesfant Fixed prettier for you, forgot to approve running actions on this PR, sorry for that.

**Review by MartinNemi03 — APPROVED** [review]
If WarpWing approved this, I'm also approving it. LGTM!

**Pull request merged**
