### PR TITLE
Added option to pick armor and calculate stats.

### PR DESCRIPTION
**Pull request by RicardormDev**
This is based on request #215 

imagen

### CODE REVIEW

**Review by asdLuis — APPROVED** [review]

**Review by metalcupcake5 — APPROVED** [review]

**Comment by metalcupcake5** [comment]
One last thing before I merge, does it edit stats based on pets? For example, when switching to magma armor with a magma cube pet, does it scale the armor stats?

**Comment by RicardormDev** [comment]
As you can see in the code what it does, is take the raw numbers from the page and modify them depending on the armor stats. The plugin will cache those to calculate the delta when the user modify any other stats (including other armor). 

You can take a look to the function I added before the weapons one.

**Comment by RicardormDev** [comment]
If you have any question just send me the # line to explain.

**Comment by metalcupcake5** [comment]
Oops, was going to merge but there's a conflict.

**Comment by RicardormDev** [comment]
> 
> 
> Oops, was going to merge but there's a conflict.

Fixed this.

**Pull request merged**
