### PR TITLE
feat: add perks

### LINKED ISSUE #1385: API perks (dungeon shop)
image

for front-end stats too

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Closes #1385 

## Examples
image
image
image

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
`dont merge yet` label until Hypixel adds Ice Essence Shop to their wiki

**Comment by DuckySoLucky** [comment]
Added ice essence
image

**Comment by DuckySoLucky** [comment]
@MartinNemi03

**Review by metalcupcake5 — APPROVED** [review]

**Comment by DuckySoLucky** [comment]
Crimson essence was added, don't merge please ;-;

**Comment by DuckySoLucky** [comment]
Added Crimson Essence
image

**Comment by DuckySoLucky** [comment]
@MartinNemi03

**Review by MartinNemi03 — APPROVED** [review]
lgtm, tested

**Pull request merged**
