### PR TITLE
feat: add new Talismans

### LINKED ISSUE #1726: New Talismans
with version 0.16 there were added a bunch of talismans (draconic talisman, ring, artifact, lighter blueTM abicase)

### LINKED ISSUE #1736: New Kuudra Tiers
In the latest Crimson Isles update, Kuudra was remade and tiers up to 5 were added. Right now, SkyCrypt only supports the first 2 tiers.

### PR DESCRIPTION
**Pull request by DuckySoLucky**
# Description 

Closes #1726 
Closes #1736
Adds talismans added in [SkyBlock Patch 0.16 - Kuudra Revamp, End Island QoL, Bits items and more!](https://hypixel.net/threads/skyblock-patch-0-16-kuudra-revamp-end-island-qol-bits-items-and-more.5143855/)

# Examples

image
image

### CODE REVIEW

**Comment by MartinNemi03** [comment]
Does the Abicase ability work with Magical Power?

**Comment by DuckySoLucky** [comment]
> Does the Abicase ability work with Magical Power?

No, forgot about that. Will add it

**Comment by DuckySoLucky** [comment]
Abicase works with MP (contacts in abiphone), they cannot stack, added back kuudra cores and added preview to MP from abicase (like hegemony)

image
image
image
image

**Review by MartinNemi03 — APPROVED** [review]
lgtm

**Pull request merged**
