### PR TITLE
Update POTM and Pet Score

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

https://canary.discord.com/channels/738971489411399761/738990246825427084/1026920027351433256
https://canary.discord.com/channels/738971489411399761/738990246825427084/1026920171354476584

## Examples 
image
image

### CODE REVIEW

**Review by dukio — CHANGES_REQUESTED** [review]
The upgrade of hotm 5->6 (can't test 6->7) doesn't match ingame:
image

image

**Comment by DuckySoLucky** [comment]
> The upgrade of hotm 5->6 (can't test 6->7) doesn't match ingame

Fixed
> http://localhost:32464/stats/dukioooo/Pomegranate#Skills

image
> http://localhost:32464/stats/thirtyvirus/Strawberry#Skills

image


image

**Review by dukio — APPROVED** [review]
lgtm tested

**Comment by MattTheCuber** [comment]
@DuckySoLucky small idea: add indicator for what pet score you are at in the pet score pop up (purple arrows)

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky small idea: add indicator for what pet score you are at in the pet score pop up (purple arrows) 

image

**Review by metalcupcake5 — APPROVED** [review]

**Pull request merged**
