### PR TITLE
slayer approximate coins spent update

### PR DESCRIPTION
**Pull request by dukio**
Edits how approx coins spent for slayer quests is being displayed:

image

### CODE REVIEW

**Review by metalcupcake5 — APPROVED** [review]
"most obviously" reads kinda weird to me

**Comment by dukio** [comment]
> "most obviously" reads kinda weird to me

for me too.... what do you think of `most notably`?

[more alternatives in this external link](https://www.wordhippo.com/what-is/another-word-for/most_importantly.html)

**Comment by metalcupcake5** [comment]
> > "most obviously" reads kinda weird to me
> 
> for me too.... what do you think of `most notably`?
> 
> [more alternatives in this external link](https://www.wordhippo.com/what-is/another-word-for/most_importantly.html)

that or `especially` i think would work better

**Comment by dukio** [comment]
Changed `most obviously` to `especially` and upstreamed.

**Pull request merged**
