### PR TITLE
Optimizations and updates

### LINKED ISSUE #986: Improve `custom-resources.js`
These are a few ways I thought of that could help improve accuracy of `custom-resource.js` when assigning items a texture:
- `nbt.tag.ExtraAttributes.id` (skyblock item id ex: `WISE_WITHER_BOOTS`) should be a top priority check for textures (also not a regex?)... so if an item has an `ExtraAttributes.id` we can instantly filter out all the textures that do not have an `nbt.tag.ExtraAttributes.id` or a matching `nbt.tag.ExtraAttributes.id`
- we should remove/ignore color attributes such as `\u00A7a` `\u00A76` `\u00A77` (example: max "Fortunate" HotM perk in FSR 1.4.2)

### LINKED ISSUE #1199: show up to 2 bonemerangs like other weapons instead of 6
https://github.com/SkyCryptWebsite/SkyCrypt/blob/2e2e979df68f1f45015df8795b0ba19d68141813/src/lib.js#L1416-L1422

This was added when bonemerangs were meta, nowadays it doesn't really make sense to still have this... I would simplify the code and keep it at top 2 like every other weapon

### LINKED ISSUE #1572: Crab Hats 2020 & 2022 don't stack anymore
So only 1 should count

### LINKED ISSUE #1689: [0.15] Pet Changes
> https://hypixel.net/threads/skyblock-patch-0-15-leveling-balancing-and-more.5123436/

### Golden Dragon
- [x] Dragons greed: Buffed Strength per 5 Magic find from flat 0.5 to 0.5% (Max 5% Strength at 50 Magic Find)

### Flying Fish
- [x] Quick Reel (Legendary) = Buffed from 75 to 80 Fishing Speed
- [x] Quick Reel (Mythic) = Buffed from 75 to 80 Fishing Speed

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Cleaned some parts of code
Updated pets, added ability to use profile stats for pet stats (Golden Dragon gold Collection)
Fixed `userProfile.tutorial is not iterable` Error [Click for Example](https://sky.shiiyu.moe/stats/beb5b536b6f1491e9c3b218b5a19063c/5bd6d546cab2431b93d672a13ef2e744) 

Closes #1689 
Closes #1572 
Closes #986 
Closes #1199

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
BRUV I suck, didn't mean to do that ;-;

**Comment by DuckySoLucky** [comment]
https://github.com/DuckySoLucky/SkyCrypt/tree/50b6eedc139eb10b95145817fb85789c1d1d7a7f

**Comment by dukio** [comment]
This PR seems to include changes of #1655 so we should wait for that to be merged first

**Comment by DuckySoLucky** [comment]
> This PR seems to include changes of #1655 so we should wait for that to be merged first

Solved

**Review by MartinNemi03 — APPROVED** [review]
lgtm, didn't test

**Pull request merged**
