### PR TITLE
Desert Scorpion Theme

### PR DESCRIPTION
**Pull request by JSanchoG**

### CODE REVIEW

**Comment by JSanchoG** [comment]
I added `image.png` file, you said you could add blur and compress it to `.webp`.

**Review by JSanchoG — COMMENTED** [review]
yes.

**Comment by nstringham** [comment]
[this comment](https://github.com/SkyCryptWebsite/SkyCrypt/pull/595#issuecomment-877741278) has some feedback that is also applicable to this PR

**Review by JSanchoG — COMMENTED** [review]
i think it works now, cant test it, because I never before used MongoDB and dont know how it works

**Review by JSanchoG — COMMENTED** [review]
i think it works now, cant test it, because nenver before used MongoDB and dont know how it works
EDIT: Switched colors: `hover` with `link` (`link` is now darker)

**Comment by nstringham** [comment]
If you need help getting mongo up and running you can either open an issue where people can help you or join the SkyCrypt Discord and ask in the nerds channel

**Review by JSanchoG — COMMENTED** [review]
done. tested

**Comment by nstringham** [comment]
it's a very light background it might look better as a light mode theme
image
image

**Comment by JSanchoG** [comment]
> it's a very light background it might look better as a light mode theme
> image
> image
> 

The theme was being created as a light theme, but i liked the contrast between cactus green and dark ui.

And also the light mode theme is just too bright to use as everyday theme.

**Review by JSanchoG — COMMENTED** [review]
.

**Comment by nstringham** [comment]
Please be patient everyone is very busy with the crystal hallows update

**Comment by nstringham** [comment]
Closing this PR because SkyCrypt doesn't really need more themes and the group of people interested in this Theme seems to be quite small.

In the long term future, I plan to add a system for third-party themes. see #597

In the short term future, Desktop Chrome users that want to use the Desert Scorpion Theme should Download the [SkyCrypt Themer Chrome Extention](https://chrome.google.com/webstore/detail/skycrypt-themer/eeeichgfigdfdmnbmfbeggaolpnhbffc) and import Desert_Scorpion_Theme.json ([MediaFire Download](https://www.mediafire.com/file/mdtiet2v7urb7oe/Desert_Scorpion_Theme.json/file)) or copy the JSON below into a JSON file
```json
{"name":"Desert Scorpion Theme","author":"Gozuk12","community":true,"images":{"bg":"https://raw.githubusercontent.com/JSanchoG/SkyCrypt/patch-3/public/resources/img/themes/desertscorpion/bg.webp"},"backgrounds":{"skillbar":{"type":"color","color":"#118d47"},"maxedbar":{"type":"color","color":"#e99c2f"}},"colors":{"logo":"#2c9254","icon":"#237543","link":"#368858","hover":"#2c9254","gold":"#f8b500"}}
```

note that the file included in this comment is not exactly the same as the PR because this PR was never finished so I fixed a few small details before uploading it

**Pull request closed without merging**
