### PR TITLE
Updated the code that parses the name of the active armor piece

### PR DESCRIPTION
**Pull request by lochyj**
Fixes issue:
https://github.com/SkyCryptWebsite/SkyCrypt/issues/1346

### CODE REVIEW

**Review by nstringham — COMMENTED** [review]
What even is `arnor_name`?

**Comment by lochyj** [comment]
> What even is `arnor_name`?

Armor_name is the name of the armor set that is displayed above the active armor set, the old code removed the stars and the skin icon `✪⍟✦`. The new code removes all characters other than `a - z`, `A - Z`, `0 - 9` and `-`. which future proof it so if an admin decides to add another symbol to an armor piece, the new code will remove it. The code also removes the upgrade icon which addresses issue: https://github.com/SkyCryptWebsite/SkyCrypt/issues/1346
This fix was suggested in that issue

The following images show what the code will do
Before:
image
After:
image

**Review by dukio — APPROVED** [review]
lgtm, didn't test

**Comment by dukio** [comment]
I checked the wiki pages that list all armor sets and `-` doesn't seem to be used in armor names currently... but still it's good to keep for future proofing (I can totally see an armor name having a - in the future)

**Comment by nstringham** [comment]
@lochyj  you should use a feature branch. This PR is all messy now because it included other changes.

**Comment by lochyj** [comment]
Now at:
https://github.com/SkyCryptWebsite/SkyCrypt/pull/1589
bc i messed up

**Pull request closed without merging**
