### PR TITLE
Change some pet emoji

### PR DESCRIPTION
**Pull request by nstringham**
this PR was formerly known as #170 but stale bot closed it because stale bot doesn't know what a draft is
### Reasons for each change:
🐈->🐆 and 🐱->🐈‍⬛ switch to a colored cat that more closely reflects the in-game head

🐇->🐰 and 🐒->🐵 switch to face variant because the pet is a head in-game

🐑->🐏 switch to a ram because the sheep pet has horns in-game

🐛->🪳 switch from a caterpillar to a cockroach to more closely approximate a silverfish

🐴->🦓 use zebra for skeleton horse because the stripes look like bones

🐛->🐜 switch from a caterpillar to an ant to more closely approximate an endermite

🗿->🪨 use new rock emoji for rock pet

### CODE REVIEW

**Comment by metalcupcake5** [comment]
wtf is a draft

**Comment by nstringham** [comment]
> wtf is a draft

It's a PR wich isn't finished yet and cannot be merged untill the author sets it to not be a draft

I'm this case I have set it to a draft because it shouldn't be merged untill major OSs add support for new Unicode fetures

**Comment by metalcupcake5** [comment]
i probably should've added /j or /s in there

**Comment by nstringham** [comment]
Android 11 and iOS 14 fully smart unicode 13 however Windows is still on Unicode 12 but the latest insider builds of Windows support Unicode 13 so as soon as those stable we can merge this thing https://blogs.windows.com/windows-insider/2020/12/10/announcing-windows-10-insider-preview-build-21277/

**Comment by nstringham** [comment]
I am making this a full PR instead of a draft but be warned if this PR is merged in its current state the following pet emoji will not be displayed correctly on windows:

black cat: 🐈‍⬛
silverfish: 🪳
rock: 🪳

will look like this on windows:
image

**Comment by dukio** [comment]
Honestly it's just a temporary windows issue that will be solved soon™️, and it only affects a few specific pets only in discord embeds (or other embeds) so I think we can just merge it now.

**Review by dukio — APPROVED** [review]

**Comment by FantasmicGalaxy** [comment]
> I am making this a full PR instead of a draft but be warned if this PR is merged in its current state the following pet emoji will not be displayed correctly on windows:
> 
> black cat: 🐈‍⬛
> silverfish: 🪳
> rock: 🪨
> 
> will look like this on windows:
> image

On Android 10 it looks about the same as the Windows picture

**Comment by nstringham** [comment]
> On Android 10 it looks about the same as the Windows picture

Also iOS 13

**Review by dukio — APPROVED** [review]

**Comment by dukio** [comment]
I would merge anyway, it's not a big deal anyway

**Pull request closed without merging**
