### PR TITLE
Profile header layout (skills, stats, additional)

### PR DESCRIPTION
**Pull request by dukio**
From my tests everything seems to be working fine but if someone else can test too would be appreciated :)

image
photo_2021-08-17_18-43-10
photo_2021-08-17_18-43-11
photo_2021-08-17_18-43-11 (2)

### CODE REVIEW

**Comment by dukio** [comment]
Changing it to draft to improve the tablet version

**Comment by dukio** [comment]
Improved the responsiveness in tablet mode and changed the way used to rescale the icons (before I was using `transform: scale(0.85)`, now I'm giving them the size `20x20px`... to do this I had to change the svg code so that the size of the svg is not forced to `24x24px` but instead `100%x100%`... I also optimized them with `svgo`)

Here's the responsive preview:

https://user-images.githubusercontent.com/2744227/129792837-b0e59d4c-60aa-4d5b-ae33-4cb2fe636286.mp4

**Review by nstringham — COMMENTED** [review]
from a design perspective I think this is good I don't really like the way the skin is small on some screen sizes but I can't think of a better way to do it and it is definitely an improvement over the old system.

I will review this PR from a technical point of view later tonight or possibly tomarrow

**Review by nstringham — APPROVED** [review]
I don't know what the SVG changes are but they don't seem to be hurting anything

the CSS HTML and JS changes in this PR all look go to me

tested and working

**Comment by dukio** [comment]
bump 👀

**Review by metalcupcake5 — APPROVED** [review]

**Review by MartinNemi03 — APPROVED** [review]
LGTM!

**Pull request merged**
