### PR TITLE
Changes to screenshot

### PR DESCRIPTION
**Pull request by Pottedplant530**
I changed the screenshot on the github to showcase themes packs ferocity ironmans and other general changes

### CODE REVIEW

**Comment by nstringham** [comment]
Two problems with this PR.
1. It also includes changes to the credits
2. It doesn't work

**Comment by nstringham** [comment]
the problem of it not working is a simple fix see https://github.com/Pottedplant530/SkyCrypt/pull/1

**Comment by nstringham** [comment]
the reason that this PR includes changes to credits seams to be that @Pottedplant530 accidentally branched [Pottedplant530:Changes-to-screenshot](https://github.com/Pottedplant530/SkyCrypt/tree/Changes-to-screenshot) from [Pottedplant530:Credits-Change](https://github.com/Pottedplant530/SkyCrypt/tree/Credits-Change) instead of [SkyCryptWebsite:master](https://github.com/SkyCryptWebsite/SkyCrypt/tree/master)

**Comment by nstringham** [comment]
Personally, I think the screenshot should probably be of the default theme.

**Comment by Pottedplant530** [comment]
@nstringham If you want to take another picture and edit the pr then be my guest

**Comment by nstringham** [comment]
I recommend closing this PR in favor of #153

**Pull request closed without merging**
