### PR TITLE
feat: add missing Sea Creatures

### LINKED ISSUE #1037: sea creatures
port the following commit from sky.lea
- [x] https://github.com/LeaPhant/skyblock-stats/commit/507ad993fa80bedad099cfc08d39506b3eb0239b

we should also look into these
- [ ] https://github.com/LeaPhant/skyblock-stats/commit/accb0e595996eed575dbd362a14da24a281196e3
- [ ] https://github.com/LeaPhant/skyblock-stats/commit/60725dffe1c13dbdded899b5e69eac186cf2fa02

### LINKED ISSUE #1336: nether sea creatures
- [ ] magma slug
- [ ] moogma
- [ ] lava leech
- [ ] pyroclastic worm
- [ ] lava flame
- [ ] fire eel
- [ ] taurus
- [ ] lord jawbus
- [ ] plhlegblast

*(taken from [here](https://hypixel-skyblock.fandom.com/wiki/Sea_Creatures#Crimson_Isle_Sea_Creatures), so may be inaccurate)*

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description 

Added Crimson Isle Sea Creature and updated icons from some sea creatures
Updated Sea Creature sorting (Now it's sorted like in `/scg`)

Closes #1037
Closes #1336 

## Example
https://user-images.githubusercontent.com/75372052/189726926-875823fb-558c-4c9f-995c-7220da1250b8.mp4

### CODE REVIEW

**Review by dukio — APPROVED** [review]
lgtm, `waiting` label until we understand what copyright/usage permissions are needed for hypixel wiki images

**Comment by dukio** [comment]
Approved. Ofc trusting we have perms for the images (think so)

Tested, lgtm

**Review by metalcupcake5 — APPROVED** [review]
didnt test

**Review by metalcupcake5 — APPROVED** [review]
tested

**Pull request merged**
