### PR TITLE
All the missing skins

### LINKED ISSUE #1560: PET_SKIN_ENDER_DRAGON_UNDEAD
{"success":true,"sales":[{"item_id":"PET_SKIN_ENDER_DRAGON_UNDEAD","start":1658505600000,"end":1658937600000,"amount":7500,"price":950}]}

### LINKED ISSUE #1605: 0.14 - New skins? (Shen's Regalia)
https://hypixel.net/threads/skyblock-patch-0-14-shens-auctions-the-hex-rng-meter-and-more.5074247/

Shen's Regalia might have new pet skins, needs to be added

### LINKED ISSUE #1617: PET_SKIN_BEE_RGBEE
`{"item_id":"PET_SKIN_BEE_RGBEE","start":1661529600000,"end":1661961600000,"amount":8000,"price":1350}`

### PR DESCRIPTION
**Pull request by dukio**
This PR adds:
- RGBee Bee skin
- Luminescent Jellyfish skin
- Undead Ender Dragon skin
- All 4 regalia rock skins (sus surprised blinking and sweating)
- A property that indicates the source of a skin (firesale, enderman slayer or regalia)

pet_skin_jellyfish_luminescent
pet_skin_bee_rgbee

Closes #1617
Closes #1560 
Closes #1605

### CODE REVIEW

**Review by metalcupcake5 — APPROVED** [review]
didnt test

**Review by MartinNemi03 — APPROVED** [review]
lgtm, didn't test

**Comment by MartinNemi03** [comment]
tho there are some conflicts due to merging #1628

**Comment by dukio** [comment]
> tho there are some conflicts due to merging #1628

done

**Pull request merged**
