### PR TITLE
Shared code and Enchantment color refactor

### PR DESCRIPTION
**Pull request by nstringham**
This PR shares a single renderLore function between the client and server and changes it so that the max level enchants are gold

### CODE REVIEW

**Comment by dukio** [comment]
About the failing `CI / check typescript`... can anything be done about it?

**Comment by nstringham** [comment]
> About the failing `CI / check typescript`... can anything be done about it?

not sure I'll look into it soon

**Comment by nstringham** [comment]
> About the failing `CI / check typescript`... can anything be done about it?

fixed in https://github.com/SkyCryptWebsite/SkyCrypt/pull/1087/commits/b3cec2f6b509ec783456943dfdae2f9b183ac5f3

**Review by metalcupcake5 — APPROVED** [review]

**Comment by nstringham** [comment]
somehow rollup got broken but it should all be good now

**Review by MartinNemi03 — APPROVED** [review]

**Pull request merged**
