### PR TITLE
Added Bal Pet

### LINKED ISSUE #609: Add Bal Pet

### PR DESCRIPTION
**Pull request by FantasmicGalaxy**
fix #609

### CODE REVIEW

**Comment by metalcupcake5** [comment]
image
real

**Review by metalcupcake5 — APPROVED** [review]
should be alphabetical as thats how i originally intended it to be but w/e

**Review by nstringham — CHANGES_REQUESTED** [review]
I'm not sure what the fix es-lint commit was trying to do but I fixed it in https://github.com/SkyCryptWebsite/SkyCrypt/pull/612

**Comment by FantasmicGalaxy** [comment]
Thanks nate, lol
It's been a while since I've made a commit for this, so I was kinda struggling with getting eslint and prettier to work

**Comment by nstringham** [comment]
@FantasmicGalaxy because we both made changes there where merge problems with #612 can you merge #613 to fix that

**Review by nstringham — APPROVED** [review]

**Comment by nstringham** [comment]
whoever merges this PR should do a squash and merge

**Review by nstringham — APPROVED** [review]

**Pull request merged**
