### PR TITLE
fix: incorrect collection tiers

### LINKED ISSUE #1859: Colouring issue
My Ghast tear collection is at T7 which it is not 

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/LeopardGecko94/Papaya#Collections
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
Should say T6
**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows 10]
- Browser: chrome

**Additional context**

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Fixes https://canary.discord.com/channels/738971489411399761/738990246825427084/1075510190717280378
Fixed #1859
> Collections being incorrect, Examples: Blaze Rod, Ghast Tear & Glowstone 

Also started with refactoring files

### CODE REVIEW

**Comment by MartinNemi03** [comment]
I'm not sure if we should show collections that are not unlocked by the player as if they are

image

Maybe we could hide it or tease at it (by making it grayscale with only the name)

**Comment by DuckySoLucky** [comment]
> I'm not sure if we should show collections that are not unlocked by the player as if they are
> 
> image
> 
> Maybe we could hide it or tease at it (by making it grayscale with only the name)

We're doing same with minions and there was an issue about them being hidden so I made collections like that 🤷

> Maybe we could hide it or tease at it (by making it grayscale with only the name)

Sure

**Comment by DuckySoLucky** [comment]
> I'm not sure if we should show collections that are not unlocked by the player as if they are
> 
> image
> 
> Maybe we could hide it or tease at it (by making it grayscale with only the name)

image

**Comment by DuckySoLucky** [comment]
Added Boss Collections
> Removed Boss collection below Dungeons category 

image
image
image

**Pull request closed without merging**
