### PR TITLE
refactor: rewrite to v2 endpoint

### LINKED ISSUE #763: Bug: unclaimed collection in dungeons (but in game it's all claimed)
**Describe the bug**
Livid collection is showing 1 unclaimed reward but the user has claimed all the collections in game (more than 1 week ago, so api is up to date).
The reward that is supposedly missing is Shadow Assassin chestplate

image

**Profile/Location**
https://sky.shiiyu.moe/stats/aajade/Raspberry#Dungeons

**Additional Info**
From what the user remembers, this happens when we merged the catacombs + master_catacombs floor kills 

**Screenshots**
image

### LINKED ISSUE #1393: Enhance stats
This issues serves the purpose to track all things that could be improved or implemented to make stats more accurate.

## This is an ever evolving list

- [ ] Pet perks that alter weapon, armor or stats directly
- [ ] Magic find from pet score
- [ ] Century cakes, see #1386
- [ ] Potion effects, see #1382 
- [ ] Dungeon shop upgrades, see #1385 
- [ ] Harp quest, see #1384 
- [ ] Accessory bag power and tuning, see #1381 
- [ ] Bestiary level (+2hp per level)
- [x] Reaper peppers (+1hp each)
- [ ] Harp intelligence bonus
- Reforges:
  - [ ] Renown
  - [ ] Loving, see #1419
- Armor set bonuses or abilities
  - [ ] Superior Dragon Armor
  - [ ] Young Dragon Armor
  - [ ] Cheap Tuxedo
  - [ ] Fancy Tuxedo
  - [ ] Elegant Tuxedo
  - [ ] Lapis Armor
  - [ ] Emerald Armor
  - [ ] Fairy Armor
  - [ ] Speedster Armor
  - [ ] Mastiff Armor
- Item abilities
  - [ ] Day Crystal
  - [ ] Night Crystal
  - [ ] Obsidian Chestplate
  - [ ] Speed Talisman
  - [ ] Speed Ring
  - [ ] Speed Artifact
  - [ ] Frozen Chicken
- Items giving personalized bonus based on kills or other things ("Kills: ", "Your Bonus: ", ...)

EHP?

---
**Also see `lib.js->getStats()`**

### LINKED ISSUE #1859: Colouring issue
My Ghast tear collection is at T7 which it is not 

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/LeopardGecko94/Papaya#Collections
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
Should say T6
**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows 10]
- Browser: chrome

**Additional context**

### LINKED ISSUE #1951: stats bug
**Describe the bug**
some of the stats aren't syncing up with my in game stats   

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**
game1
game2

**Desktop (please complete the following information):**

- OS:  Windows 10
- Version 1.19.4

### LINKED ISSUE #2007: Rift race never shows as completed
**Describe the bug**
Rift race never shows any tiers as completed.

**Profile/Location**
For example, open https://sky.shiiyu.moe/stats/DeathStreeks/Blueberry#Misc and scroll down a bit to the Races section. You'll see each of it having filled circle meaning all race tiers are completed, except the Rift, all circles are empty inside.

**Additional Info**
N/A

**Expected behavior**
Expected the race to be shown as completed (the circles having white filled inside them)

**Screenshots**
Screenshot from 2023-08-20 02-30-25

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Firefox Developer Edition 117.0b9

**Additional context**
N/A

### LINKED ISSUE #2083: doesn't show my profile but shows my friends
**Describe the bug**
gives error when searching for my ign
**Profile/Location**
https://sky.shiiyu.moe/stats/fire__ferret/Strawberry

**Expected behavior**
the website will show me my page

**Screenshots**
doesn't show mine
image
shows other's
image

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser brave, chrome
- Version idk

**Additional context**
no additional context

### LINKED ISSUE #2085: Unable to view own profile, says " Cannot read properties of undefined (reading 'none') "
When i search for my own profile it says " Cannot read properties of undefined (reading 'none') ".

https://sky.shiiyu.moe/stats/the501stgamer

I expected to be able to view my profile as usual but unfortunately no, I can still view my friends profiles though.

I'm unable to link a screenshot currently.

- OS: Mac OS
- Chrome
- Unsure

### LINKED ISSUE #2086: When trying to access my profile it says: Cannot read properties of undefined (reading 'none')
My profile is this: https://sky.shiiyu.moe/stats/b1naryc0d3/Plancke
I was using an AOTD ,Strong Drag Armor and a Common Griffin.
OS: Win11
Browser: Opera GX

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Still WIP, made in case someone wants to test / fix some bugs

Fixes #2083
Fixes https://github.com/SkyCryptWebsite/SkyCrypt/issues/1859
Fixes https://github.com/SkyCryptWebsite/SkyCrypt/issues/763
Fixes https://github.com/SkyCryptWebsite/SkyCrypt/issues/1393
Fixes https://github.com/SkyCryptWebsite/SkyCrypt/issues/1951
Fixes https://github.com/SkyCryptWebsite/SkyCrypt/issues/2007
Fixes #2085
Fixes #2086

### CODE REVIEW

**Comment by Zickles** [comment]
me when pr aint urgent

**Comment by DuckySoLucky** [comment]
> me when pr aint urgent

cuz it ain't and it's still WIP

**Review by metalcupcake5 — APPROVED** [review]

**Comment by ptlthg** [comment]
<details>
<summary>LGTM!</summary>
I am a SkyCrypt dev for sure
</details>

**Comment by DuckySoLucky** [comment]
> LGTM!

rewrite farming contents at SkyCrypt when

**Pull request merged**
