### PR TITLE
Update themes.js

### PR DESCRIPTION
**Pull request by JSanchoG**
New Theme - Bloody Scorpion
bg
bg_blur

### CODE REVIEW

**Comment by nstringham** [comment]
Hey @JSanchoG I have a few things about your PR that need some work

`bg_blur` should be the same image as `bg` but blurred

We usually only use 16x textures for pack backgrounds Dandelion is a good choice if you don't have a preference

**Comment by JSanchoG** [comment]
> Hey @JSanchoG I have a few things about your PR that need some work
> 
> `bg_blur` should be the same image as `bg` but blurred
> 
> We usually only use 16x textures for pack backgrounds Dandelion is a good choice if you don't have a preference
> 
> 

If I will only change the 'bg_blur' image is there a chance to add this new theme without changing texture pack?

If not, is there a chance to add this new theme If I Update 'bg_blur' and texture pack?

**Comment by nstringham** [comment]
@JSanchoG sorry I accidentally posted my comment before I was done writing it. As I said in the second half the background should be a screenshot of something in skyblock

**Comment by nstringham** [comment]
Also if you want you can just do `bg.png` and I'll do the compression and bluring for you

**Comment by JSanchoG** [comment]
'/visit Gozuk12' and look back. This is the screenshot.

Is it has to be screenshot from Hub?
Or can i do it in redstone room (dungeons)?

**Comment by JSanchoG** [comment]
> @JSanchoG sorry I accidentally posted my comment before I was done writing it. As I said in the second half the background should be a screenshot of something in skyblock

And sry,  but whats PR?

**Comment by JSanchoG** [comment]
> Also if you want you can just do `bg.png` and I'll do the compression and bluring for you

Ill just do new branch or sth idk how its called and fix everything.

**Comment by nstringham** [comment]
> And sry, but whats PR?

PR is short for pull request

**Comment by nstringham** [comment]
> Ill just do new branch or sth idk how its called and fix everything.

Ok I'll close this then

**Pull request closed without merging**
