### PR TITLE
Defer imgs

### PR DESCRIPTION
**Pull request by shadowtime2000**
Basic deferring of offscreen images like the ones found the navbar.

### CODE REVIEW

**Comment by nstringham** [comment]
wouldn't it be better to use `loading="lazy"`

**Comment by shadowtime2000** [comment]
@nstringham `loading="lazy"` loads when the image is a calculated distance away from the viewport, and since the navbar starts in view of the user, the images are just fetched normally.

**Comment by nstringham** [comment]
the files deferred by this PR total 67 kb which adds about 0.007 seconds to page load time on 4G and they are cached so they will only be downloaded on the first page load.

I don't think the added complexity is worth the very small performance gains.

If these images are a problem I would recommend compressing the pack icons using a tool like Squoosh.

**Comment by nstringham** [comment]
I recommend closing this PR in favor of #381

**Pull request closed without merging**
