### PR TITLE
feat(constants): add lava sea creature armor set

### PR DESCRIPTION
**Pull request by MattTheCuber**
yes

### CODE REVIEW

**Review by DuckySoLucky — APPROVED** [review]
yes (lgtm, didn't test)

**Comment by MattTheCuber** [comment]
14d ago 💀

**Comment by DuckySoLucky** [comment]
> 14d ago 💀

Welcome to SkyCrypt 💀

**Review by MartinNemi03 — APPROVED** [review]
lgtm, tested (on 50 profiles)

**Comment by MattTheCuber** [comment]
Didn't mean to close, thought was merged and deleted my fork

**Pull request merged**
