### PR TITLE
seperate css into files for pages

### PR DESCRIPTION
**Pull request by nstringham**
this PR continues the work started in #878 by moving styles specific to the stats page into `stats.scss`

this PR also includes a few minor improvements:
- remove unused ReCaptcha code
- remove unused styles
- organize styles order

### CODE REVIEW

**Review by MartinNemi03 — APPROVED** [review]

**Comment by dukio** [comment]
@MartinNemi03 recaptcha is actually not used in production?

**Review by dukio — APPROVED** [review]
lgtm, tested

But I see there's some conflicts now with shared.scss...

**Review by metalcupcake5 — APPROVED** [review]
didnt test

**Comment by MartinNemi03** [comment]
> @MartinNemi03 recaptcha is actually not used in production?

It's not, so it's safe to remove.

**Comment by nstringham** [comment]
fixed conflicts

**Pull request merged**
