### PR TITLE
added some spec enchs

### PR DESCRIPTION
**Pull request by Untitled**
https://github.com/SkyCryptWebsite/SkyCrypt/issues/28

### CODE REVIEW

**Comment by WarpWing** [comment]
Ah, this makes em fully colored in. Thank you for this commit :D Will merge shortly

**Comment by metalcupcake5** [comment]
This won't fix the problem, it will detect prot 6 and go to color that, then move on.

**Comment by WarpWing** [comment]
Hmmmm. My bad metal. I'll let you take it from here

**Comment by apollyon600** [comment]
How did this become the problem if you forked it from the og website?
Unless you guys rewrote the code.

**Comment by metalcupcake5** [comment]
It was a problem with Lea's site aswell, we just didn't fix it because nobody really uses blast prot, proj prot, and fire prot, much less the t6 versions of them

**Pull request merged**
