### PR TITLE
[URGENT] fix: TS error, causing JS elements not to load

### LINKED ISSUE #2022: Broken features on specific profile
**Describe the bug**
When trying to view my main profile on SkyCrypt, I'm welcomed with a strange URL (https://sky.shiiyu.moe/stats/0696189846e54593af0e0e23b78cd9d1/8dc90ad9-1fbb-43af-a07a-8255c7c7f32c) and many broken features, such as, but not limited to:

- Level progression, Skills progression and stats not showing up at the top of the page
- Skin on the left of the page is not there
- No info showing up when hovering or clicking on an item
- Unable to interact and open menus, such as inventories and missing accessories/pets
- Other informations not being displayed

**Profile/Location**
https://sky.shiiyu.moe/stats/Teos_Dinok/Mango

**Additional Info**
Any other profile work fine, and I was able to confirm that the issue is not local, as a friend of mine checked my SkyCrypt profile and witnessed the same results.
The profile seems to update whenever there is a change (such as switching pets, switching lobbies, having more or less coins in the bank/purse).

**Expected behavior**
I would expect to be able to view my main profile as I would any other working profile, mine and other players'.

**Screenshots**
I don't believe screenshots are necessary, since the issue doesn't seem to be only on my end.

**Desktop:**

- Windows 10
- Chrome
- Version 116.0.5845.141

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Fixes #2022
Fixes https://canary.discord.com/channels/738971489411399761/748625263893545042/1150161156196016368

### CODE REVIEW

**Comment by Zickles** [comment]
i wonder who caused this error in the first place ducky

**Comment by DuckySoLucky** [comment]
> i wonder who caused this error in the first place ducky

TypeScript being TypeScript

**Comment by Ascynx** [comment]
> > i wonder who caused this error in the first place ducky
> 
> TypeScript being TypeScript

Shrimply incredible

**Comment by Zickles** [comment]
no fucking way it was erroring that hard bc of wrong type of quotes lmao

**Review by Zickles — APPROVED** [review]

**Comment by TeosDinok** [comment]
Hey there, it's been a few days since the commit was merged, but I'm still having these TS errors, and these results both on my Mango profile and on AxM_'s Cucumber profile. Is this supposed to be the case?

both profiles:
https://sky.shiiyu.moe/stats/Teos_Dinok/Mango
https://sky.shiiyu.moe/stats/axm_/cucumber

**Comment by DuckySoLucky** [comment]
> Hey there, it's been a few days since the commit was merged, but I'm still having these TS errors, and these results both on my Mango profile and on AxM_'s Cucumber profile. Is this supposed to be the case?
> 
> both profiles:
> https://sky.shiiyu.moe/stats/Teos_Dinok/Mango
> https://sky.shiiyu.moe/stats/axm_/cucumber

Heya, it hasn't been merged to production yet so sadly it's not live yet. @metalcupcake5 can you merge dev into prod?

**Pull request merged**
