### PR TITLE
added rat pet

### PR DESCRIPTION
**Pull request by boblovespi**

### CODE REVIEW

**Comment by boblovespi** [comment]
need to wait on hypixel api before testing this

**Comment by dukio** [comment]
There's also need to be something done here to make it say Morph correctly:
https://github.com/SkyCryptWebsite/SkyCrypt/blob/31a3616178091d6e67ef0deb4bf3f2834e212e78/src/lib.js#L2555

image

**Review by dukio — CHANGES_REQUESTED** [review]
isMorph and isMount should be const instead of let, otherwise all good

**Comment by boblovespi** [comment]
image
note: health and crit damage have been swapped around

**Review by metalcupcake5 — APPROVED** [review]
hi yes it good

**Pull request merged**
