### PR TITLE
nether talismans

### LINKED ISSUE #1249: New accessories
# Odger's <tier> Tooth
1. COMMON [Odger's Bronze Tooth](https://sky.shiiyu.moe/head/accc4432efe08c88530ac084fea6526641a207d78e637e41f7a4e5dcfdaaa162)
2. UNCOMMON [Odger's Silver Tooth](https://sky.shiiyu.moe/head/c2d41b2279abce5fd626923b61e3ab98dce4972417289ee2b73214c0aaba841e)
3. RARE [Odger's Gold Tooth](https://sky.shiiyu.moe/head/42024901024636f1c074e6562285f4cc9fd3da2885d4010cee52cc0696d2f96a)
4. EPIC [Odger's Diamond Tooth](https://sky.shiiyu.moe/head/a2680a28962e9ad2d4872d06fba2cc60824fbb2d0824e42d958575b7563884aa)

# Jacobus Register
image
image
https://sky.shiiyu.moe/head/3b648b9a44e280bcdf25f4a66a97bd5c33542e5e82415e15b475c6b999b8d635

### PR DESCRIPTION
**Pull request by metalcupcake5**
adds #1249 and a couple other new talismans
image
image
image

### CODE REVIEW

**Review by MartinNemi03 — APPROVED** [review]

**Review by dukio — APPROVED** [review]
I'm on mobile but looks good, didn't test

**Comment by dukio** [comment]
@metalcupcake5 I can't find any info about that Pulse Ring, where did you find it?

**Comment by metalcupcake5** [comment]
also in items api which is how I got the head

**Pull request merged**
