### PR TITLE
MongoDB error fix `TypeError: cannot read property 'date'/'last_updated' of undefined`

### PR DESCRIPTION
**Pull request by dukio**
Basically the code was expecting a query with no results found to return `null`, while for me in localhost it returns `undefined` instead.

But why is it working with `null` on Nate PC and on the server? 🤔

### CODE REVIEW

**Comment by nstringham** [comment]
Wouldn't it be better to use ` == undefined` so that we are checking for nullishness instead of truthiness

**Comment by dukio** [comment]
> Wouldn't it be better to use ` == undefined` so that we are checking for nullishness instead of truthiness

Updated using ` == undefined` or `!= undefined`

**Review by nstringham — APPROVED** [review]
you could also do `== null` if you want to change less but this works

**Review by nstringham — APPROVED** [review]
I tested this on my PC and everything works

**Pull request merged**
