### PR TITLE
[0.12.3] M7 Update: Catacombs level above 50

### LINKED ISSUE #1168: [0.12.3] M7 Update: Catacombs level above 50
Thread: https://hypixel.net/threads/0-12-3-master-mode-7.4845290/

Catacombs level can go above 50 now

### PR DESCRIPTION
**Pull request by DuckySoLucky**
# Description

Closes #1168 

# Examples
image

### CODE REVIEW

**Comment by dukio** [comment]
@DuckySoLucky if you can merge/do this https://github.com/DuckySoLucky/SkyCrypt/pull/2 then for me this is ✅

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky if you can merge/do this [DuckySoLucky#2](https://github.com/DuckySoLucky/SkyCrypt/pull/2) then for me this is ✅

Forgot about that, ty

**Review by dukio — APPROVED** [review]
lgtm tested

**Review by metalcupcake5 — APPROVED** [review]
didnt test

**Pull request merged**
