### PR TITLE
netherrack looking sunshade

### PR DESCRIPTION
**Pull request by metalcupcake5**
image

### CODE REVIEW

**Comment by dukio** [comment]
Can't find any info on this... source???

**Comment by metalcupcake5** [comment]
i've only found it in items api so closing for now

**Comment by dukio** [comment]
@metalcupcake5 I've added the "dont merge yet" label so maybe we can keep it open, but with that label? what do you think?

If they added it they will probably release it sometime soon I guess...

**Comment by metalcupcake5** [comment]
image

**Comment by MartinNemi03** [comment]
> image

nvm, look into the patch notes
https://hypixel.net/threads/may-11-sunshade-patch.4944569/

**Comment by metalcupcake5** [comment]
minikloon trollage

**Review by dukio — APPROVED** [review]

**Comment by dukio** [comment]
Well then... can be merged now xd

**Pull request merged**
