### PR TITLE
feat: add missing skins in pets section

### LINKED ISSUE #982: Missing pet skins section
image

### PR DESCRIPTION
**Pull request by DuckySoLucky**
# Description

Closes #982 

# Examples (Scroll down)
> Refraction 
image
> DuckySoSkilled
image
> DeathStreeks
image

### CODE REVIEW

**Review by dukio — CHANGES_REQUESTED** [review]
See https://github.com/DuckySoLucky/SkyCrypt/pull/9
There's still work to be done after the PR merge

**Comment by dukio** [comment]
I'll add the waiting tag cause the typescript issues needs to be resolved (you or someone else)

**Comment by DuckySoLucky** [comment]
> I'll add the waiting tag cause the typescript issues needs to be resolved (you or someone else)

Solved

**Review by dukio — CHANGES_REQUESTED** [review]
Overall is good but I would improve it like discussed here: https://discord.com/channels/738971489411399761/820755886262976553/1029145305268105246 (private channel)

**Comment by DuckySoLucky** [comment]
Added new Kuudra tiers
image
Added Description to Item Skins
image
image
image

**Review by metalcupcake5 — APPROVED** [review]

**Pull request closed without merging**
