### PR TITLE
fix: hotm

### LINKED ISSUE #2250: Dragons killed in less than 1 second are shown without the "0." in front.
**Describe the bug**
In Misc, Dragons section, if you have helped killing a dragon and it died in less than 1 second, it is shown without the "0." front, so if you have a dragon killed in 0.950 seconds, as in my case, it will show as if it were 950 seconds.

**Profile/Location**
[Rubyrak on Watermelon](https://sky.shiiyu.moe/stats/Rubyrak/Watermelon#Misc)

**Expected behavior**
Show, at least in this case, 0.950s instead of 950s

**Screenshots**
image
image
I know that the second image does not show the decimals, but it looks like it takes less than 1 second.

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [Google Chrome]
- Version [124]

### LINKED ISSUE #2263: HoTM tree
New Heart of the mountain perks shows wrong, some doesn't show up(Rags of riches), and some have wrong max level(example Eager Adventurer has 50 max levels on site, while it has 100 in game, it still shows 94/50 tho)

Profile: https://sky.shiiyu.moe/stats/adultk1d/Banana

- OS: Windows 10, Android
- Browser: Google Chrome

### LINKED ISSUE #2273: HotM Tree shows wrong
New HotM tree updated, but there are lots of perks shows wrong on website.

Profile: https://sky.shiiyu.moe/stats/XiaoHei_awa/Banana#Skills

### PR DESCRIPTION
**Pull request by averithefox**
Fixes #2273, Fixes #2263

Fixed HOTM tree, broken by the mining update

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
Well- there goes all @Shiiyu work :kek:

**Comment by Shiiyu** [comment]
> Well- there goes all @Shiiyu work :kek:

I only had HOTM 10 left and was going to finish this morning, but you beat me to it haha. 

Though you did reformat things in a way similar to how I did things, I see some minor changes and some other small things I'll end up changing before this pr would potentially be merged, although it's only a small concern.

The big issue is that you've changed the packages, especially because it's in a way that things won't actually run at all due to rollup erroring. I am also unsure why the gitignore was changed either when it shouldn't have. These things need to be reverted.

Lastly, please move the dragon changes to a separate pr.

Once these things are done, I'll make the few minor changes to hotm and then get your pr through.

**Review by Shiiyu — CHANGES_REQUESTED** [review]
Please fix these things before the pr is reconsidered

**Comment by Shiiyu** [comment]
Somehow managed to revert to an older commit when trying to pull origin :sob:

**Review by Shiiyu — APPROVED** [review]

**Pull request merged**
