### PR TITLE
Added pet skins (cleaned)

### PR DESCRIPTION
**Pull request by dukio**
PR to add support for pet skins:

image
Visible skins in the pets section

image
Added statistics for unique pet skins

image
Added skin name in the first line of the lore (same as in-game)

Full preview: https://i.imgur.com/6RtFpRu.png
Current SkyCrypt: https://i.imgur.com/aCLTCwX.png

I would just note that unfortunately I do not own all the skins so I am unable to test:
 - ~~Pink Sheep~~ tested, works
 - ~~Smiling Rock~~ tested, works
 - ~~Derpy Rock~~ tested, works
 - ~~Embarrassed Rock~~ tested, works
 - ~~"golden-text" counter for "Unique Pet Skins"~~ tested, works

But everything should work fine (unless there's some name mismatching between the skin item and the pet skin id).

Hopefully this time I made the PR correctly 🤞

### CODE REVIEW

**Review by MartinNemi03 — APPROVED** [review]
Looks good to me. I'll let other review this PR, but I approve.

**Comment by dukio** [comment]
@MartinNemi03 I also added the new silverfish skin coming with the next fire sale in 25h (from this comment)

**Comment by dukio** [comment]
47ff1b6 fixes a typo, also I have tested with all pet skins and everything works perfectly now: https://i.imgur.com/HQJbPUb.png

**Comment by MartinNemi03** [comment]
> 
> 
> [47ff1b6](https://github.com/SkyCryptWebsite/SkyCrypt/commit/47ff1b64b430141b0ccba49301ce84baebeb3669) fixes a typo, also I have tested with all pet skins and everything works perfectly now: https://i.imgur.com/HQJbPUb.png

Ok, nice. 
@metalcupcake5 @boblovespi Please review, thank you.

**Review by metalcupcake5 — APPROVED** [review]
Looks good, appears to be tested from the ss

**Pull request merged**
