### PR TITLE
feat: add chili pepper to collections

### LINKED ISSUE #1582: Chili Pepper (new collection, enchants, more?)
> Chili Pepper

Chili Peppers are a new item which drop somewhat frequently from Inferno Minions running Hypergolic Fuel.
You should get between 5 and 30 per minion per day, depending on how many minions you have on your island.
It's not required to be able to kill the Inferno Demonlord in order to run Inferno Minions.

1659556585064.png
Self-descriptive!​

The Chili Pepper collection has 9 recipe unlocks with many consumables useful for all players.

1659556869101.png 1659556863598.png
Habanero Tactics for your armor pieces at Chili Pepper VII
Used with the Smoldering Polarization from the consumable at Chili Pepper I

1659556987145.png
Alternative Sulphuric Coal recipe from Chili Pepper II, which should reduce Hypergolic Gabagool price

1659557098474.png

1659557061536.png
Jalapeno Books to upgrade the stats on your Deployables' auras (1 book per item, doesn't stack)​

There are more items in the collection so make sure to check it out in-game.

https://hypixel.net/threads/august-5-chili-pepper-update.5057174/

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description 

Closes #1582

## Type of change
- [x] New Feature

### CODE REVIEW

**Review by MartinNemi03 — APPROVED** [review]
lgtm, didn't test

**Comment by dukio** [comment]
The head doesn't work: https://sky.shiiyu.moe/head/f859c8df1109c08a756275f1d2887c2748049fe33877769a7b415d56eda469d8c

image


http://localhost:32464/stats/DeathStreeks/Blueberry#Collections

**Comment by DuckySoLucky** [comment]
@dukio  Oops, somehow `c` got at the end of texture. Correct one is `f859c8df1109c08a756275f1d2887c2748049fe33877769a7b415d56eda469d8`

More Details:
<details>
   <summary>NBT of Chili Pepper (bazaar) </summary>
   
   ````js
{
    id: "minecraft:skull",
    Count: 1b,
    tag: {
        SkullOwner: {
            Id: "3d47abaa-b40b-3826-b20c-d83a7f053bd9",
            Properties: {
                textures: [{
                    Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg1OWM4ZGYxMTA5YzA4YTc1NjI3NWYxZDI4ODdjMjc0ODA0OWZlMzM4Nzc3NjlhN2I0MTVkNTZlZGE0NjlkOCJ9fX0="
                }]
            }
        },
        display: {
            Lore: ["§8Uncommon commodity", "", "§7Buy price: §6159,998 coins", "§7Sell price: §672,780 coins", "", "§eClick to view details!"],
            Name: "§aChili Pepper"
        }
    },
    Damage: 3s
}
   ````

</details>

<details>
   <summary>Decoded texture data </summary>
   
   ````json
{
    "textures":{
       "SKIN":{
          "url":"http://textures.minecraft.net/texture/f859c8df1109c08a756275f1d2887c2748049fe33877769a7b415d56eda469d8"
       }
    }
 }
   ````

</details>

**Review by dukio — APPROVED** [review]
lgtm tested

**Review by metalcupcake5 — APPROVED** [review]
did not test

**Pull request merged**
