### PR TITLE
Added pet skins

### PR DESCRIPTION
**Pull request by dukio**
Hi, first time making a pull request so hopefully I did everything correctly... if not please let me know 😄 

This PR simply adds the support for pet skins.
The skins are stored in the constants (pet.js). The code checks if the pet has a skin and if the skin texture exists in the costants, if so it replaces the default texture with the skin one.

Preview using my profile: https://i.imgur.com/qgpNKn5.png
My profile: https://sky.shiiyu.moe/stats/dukioooo/Pomegranate

### CODE REVIEW

**Comment by metalcupcake5** [comment]
Why are there so many unnecessary changes?

**Comment by dukio** [comment]
> Why are there so many unnecessary changes?

vscode unified the indentation style of the files, converting the tabs into spaces....

I noticed it but thought it wasn't an issue, if anything a "fix". 


If you want I can resubmit without those changes

**Comment by nstringham** [comment]
@dukio it is usually a good idea to only include changes relevant to the PR if you want you can make a separate PR for code style

**Comment by MartinNemi03** [comment]
I don't think it's really an issue. It's something that can happen and if it doesn't alternate the functionality of that code, it's okay for my point of view.

**Comment by nstringham** [comment]
> I don't think it's really an issue. It's something that can happen and if it doesn't alternate the functionality of that code, it's okay for my point of view.

Yes but it makes it harder to review because it's not clear what exactly the PR is doing

**Comment by dukio** [comment]
Ok, I'll make another PR 😄

**Comment by metalcupcake5** [comment]
^ that, and also at least making them separate commits would be better than just one commit

**Pull request closed without merging**
