### PR TITLE
Update Hypixel+ to 0.19.5

### PR DESCRIPTION
**Pull request by ic22487**
Updates Hypixel+ to 0.19.5

### CODE REVIEW

**Review by DuckySoLucky — APPROVED** [review]
lgtm, don't merge before Christmas pls, ty <3

**Comment by ic22487** [comment]
> lgtm, don't merge before Christmas pls, ty <3

💀

**Comment by metalcupcake5** [comment]
will do

**Comment by DuckySoLucky** [comment]
> will do

ty ily <3

**Comment by ic22487** [comment]
No idea why the conflict thing is happening
will re-pr once 0.19.6 releases

**Pull request closed without merging**
