### PR TITLE
Better theming

### PR DESCRIPTION
**Pull request by nstringham**
This PR adds a more robust theming system including support for light themes it also adds a Candycane theme to demonstrate the new light mode.
image

### CODE REVIEW

**Comment by metalcupcake5** [comment]
madlad

**Comment by nstringham** [comment]
BTW the reason this PR looks like it changes so many files is that SkyCryptWebsite:themes is behind SkyCryptWebsite:master

**Comment by MartinNemi03** [comment]
> 
> 
> BTW the reason this PR looks like it changes so many files is that SkyCryptWebsite:themes is behind SkyCryptWebsite:master

Yeah, I've noticed that.. You could've messaged me, now this PR is impossible to review :NotLikeThis:

**Comment by nstringham** [comment]
I'm going to close this PR and open a new one that should help

**Comment by nstringham** [comment]
#163

**Pull request closed without merging**
