### PR TITLE
remove fallback for backdrop-filter

### PR DESCRIPTION
**Pull request by nstringham**
Firefox is about to finally add support for `backdrop-filter` in Firefox 103 (see [caniuse/css-backdrop-filter](https://caniuse.com/css-backdrop-filter))

once this feature is fully rolled out we can safely remove support for browsers that do not have this feature

### CODE REVIEW

**Comment by nstringham** [comment]
Firefox 103 came out today

**Comment by nstringham** [comment]
I'm not sure how long it will take for people to update

**Comment by dukio** [comment]
From caniuse relative usage it looks like a lot of people are still using older versions....

**Review by metalcupcake5 — APPROVED** [review]

**Comment by MartinNemi03** [comment]
I think we can safely assume now most Firefox users use 103.

**Pull request merged**
