### PR TITLE
feat: add missing skins

### LINKED ISSUE #1706: PET_SKIN_BLACK_CAT_PURRANORMAL
> https://hypixel.net/threads/spooktacular-halloween-2022.5129719/

image
purranormal-skin

### LINKED ISSUE #1710: New Sheep skins
{
  "sales": Array[3][
    {
      "amount": 5000,
      "end": 1665590400000,
      "item_id": "PET_SKIN_SHEEP_WHITE_WOOLY",
      "price": 650,
      "start": 1665158400000
    },
    {
      "amount": 7500,
      "end": 1665590400000,
      "item_id": "PET_SKIN_SHEEP_CHROMA_WOOLY",
      "price": 1350,
      "start": 1665158400000
    },
    {
      "amount": 5000,
      "end": 1665590400000,
      "item_id": "PET_SKIN_SHEEP_BLACK_WOOLY",
      "price": 650,
      "start": 1665158400000
    }
  ],
  "success": true
}

### LINKED ISSUE #1729: new skins
{"success":true,"sales":[{"item_id":"PET_SKIN_SNOWMAN_ICE_GOLEM","start":1666368000000,"end":1666800000000,"amount":7500,"price":650},{"item_id":"PET_SKIN_MOOSHROOM_COW_MOOCELIUM","start":1666368000000,"end":1666800000000,"amount":7500,"price":650}]}

### LINKED ISSUE #1757: PET_SKIN_TIGER_NEON
```json
    {
      "item_id": "PET_SKIN_TIGER_NEON",
      "start": 1667581200000,
      "end": 1668013200000,
      "amount": 8000,
      "price": 1350
    }
```

### LINKED ISSUE #1783: PET_SKIN_CHICKEN_TURKEY
```json
    {
      "item_id": "PET_SKIN_CHICKEN_TURKEY",
      "start": 1669309200000,
      "end": 1669395600000,
      "amount": 5000,
      "price": 650
    }
```

Skin data: `ewogICJ0aW1lc3RhbXAiIDogMTYzOTI4ODg3NDQxNywKICAicHJvZmlsZUlkIiA6ICI0NDAzZGM1NDc1YmM0YjE1YTU0OGNmZGE2YjBlYjdkOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJQWFkxIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzNmM1MTUzZDAwZGQ3MzU2ZWI5YWE0MzhlOWYxZmU2NjhjZTNlMjY0OTg3OTNlZDMzYzEzOTA4OTU1Yjk1ZTQiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ==`

### LINKED ISSUE #1802: WITHER_ARMOR_CELESTIAL Skins
```json
    {
      "item_id": "MAXOR_CELESTIAL",
      "start": 1670605200000,
      "end": 1671037200000,
      "amount": 8000,
      "price": 1350
    },
    {
      "item_id": "GOLDOR_CELESTIAL",
      "start": 1670605200000,
      "end": 1671037200000,
      "amount": 8000,
      "price": 1350
    },
    {
      "item_id": "NECRON_CELESTIAL",
      "start": 1670605200000,
      "end": 1671037200000,
      "amount": 8000,
      "price": 1350
    },
    {
      "item_id": "STORM_CELESTIAL",
      "start": 1670605200000,
      "end": 1671037200000,
      "amount": 8000,
      "price": 1350
    }
```

Textures can be found here https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/872/commits/0927927db27cf761e020e7bbdc387f44fa0c7520

### LINKED ISSUE #1809: BACKPACK & ROCK_PET Skin
Textures can be found at https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/commit/bebdbe0971a2fe83b7d1c27fe3e3d3fd139b8f59

Note: Rock pet skin is from advent calendar
image

### PR DESCRIPTION
**Pull request by DuckySoLucky**
> This PR is up to date #1745 (Made new PR because old one is outdated and half of stuff is broken, resource pack caching, reindeer pet etc..)
## Description

Adds missing pet skins

Closes #1729 
Closes #1710 
Closes #1706
Closes #1757 
Closes #1783 
Closes #1802 
Closes #1809 

# Animations for skins are missing
> Following skins are missing animations: `PET_SKIN_BLACK_CAT_PURRANORMAL`, `PET_SKIN_SHEEP_CHROMA_WOOLY`, `PET_SKIN_TIGER_NEON`, `GOLDOR_CELESTIAL`, `NECRON_CELESTIAL`, `STORM_CELESTIAL` and `PET_SKIN_ROCK_NORTH_STAR`

I think we should merge this PR so users can actually see skins in pets menu. Just having texture is better than having nothing for animated ones. If this PR gets merged we should make issue for animated skins

### CODE REVIEW

**Comment by MartinNemi03** [comment]
> I think we should merge this PR so users can actually see skins in pets menu. Just having texture is better than having nothing for animated ones. If this PR gets merged we should make issue for animated skins

Definitely, we should keep track of these types of things we're missing.

**Review by MartinNemi03 — APPROVED** [review]
anyway, lgtm, tested

**Comment by DuckySoLucky** [comment]
Added new skins, animations are missing for following skins
`LUNAR_RABBIT_HAT`, `PET_SKIN_RABBIT_LUNAR`, `WITHER_GOGGLES_CYBERPUNK`, `WITHER_GOGGLES_CELESTIAL`,  `PET_SKIN_REINDEER_AURORA` and `PET_SKIN_GRIFFIN_REINDRAKE`

**Comment by MartinNemi03** [comment]
> Added new skins, animations are missing for following skins `LUNAR_RABBIT_HAT`, `PET_SKIN_RABBIT_LUNAR`, `WITHER_GOGGLES_CYBERPUNK`, `WITHER_GOGGLES_CELESTIAL`, `PET_SKIN_REINDEER_AURORA` and `PET_SKIN_GRIFFIN_REINDRAKE`

lgtm, re-tested
image

**Pull request merged**
