### PR TITLE
feat: add `Item Value` to description of items

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Adds `Item Value` to description of items

## Examples 

image
image

### CODE REVIEW

**Comment by MattTheCuber** [comment]
Very cool PR!

**Comment by MattTheCuber** [comment]
I would round the networth value to not have decimals, also maybe a brighter color for the value?

**Comment by Baltrazx** [comment]
`Item Value: 2,000,000 (2M)` suggested format for the extra lore

**Comment by DuckySoLucky** [comment]
New lore format

image

**Review by MartinNemi03 — APPROVED** [review]
lgtm, tested
_only thing would maybe be capitalizing `Item value: x coins` to `Item Value: x Coins`, but that's just a detail_

**Comment by DuckySoLucky** [comment]
> lgtm, tested _only thing would maybe be capitalizing `Item value: x coins` to `Item Value: x Coins`, but that's just a detail_

Done

**Pull request merged**
