### PR TITLE
feat: add trophyFish

### LINKED ISSUE #1462: API trophy_fish
image

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Closes #1462

## Examples
image
image
image
image

### CODE REVIEW

**Comment by metalcupcake5** [comment]
oops wrong button
marking this as draft until dukio finishes

**Comment by LeaPhant** [comment]
Is the front-end for this actually being worked on? Might do it cause I'm tired of checking my fishies through a discord bot but don't wanna interfere with existing work.

**Comment by DuckySoLucky** [comment]
> Is the front-end for this actually being worked on? Might do it cause I'm tired of checking my fishies through a discord bot but don't wanna interfere with existing work.

@dukio

**Comment by dukio** [comment]
> > Is the front-end for this actually being worked on? Might do it cause I'm tired of checking my fishies through a discord bot but don't wanna interfere with existing work.
> 
> @dukio

No I actually haven't started this yet, if you want you can maybe just print them out in a row and then I'll do the further styling.

With all the other PRs I don't think I'll have time to do this before this Friday

**Comment by DuckySoLucky** [comment]
## Example
image
image
image

**Review by MartinNemi03 — CHANGES_REQUESTED** [review]
Before reviewing, I would like to resolve the failing typescript check.
Not sure what causes it tho, so I'll investigate it a bit.

**Comment by DuckySoLucky** [comment]
> Before reviewing, I would like to resolve the failing typescript check.
> Not sure what causes it tho, so I'll investigate it a bit.

Front end isn't really done, so imo u shouldn't merge yet. About TS error I'm not sure either.

**Review by MartinNemi03 — CHANGES_REQUESTED** [review]
~~When merged with development, it doesn't work on many featured profiles~~
nevermind, my local branch didn't update even tho i've deleted it just to refresh all of them.. time to test it then

**Review by MartinNemi03 — CHANGES_REQUESTED** [review]
So after testing it, I have a few things..
- `jjww2`'s profile doesn't load (`Cannot read properties of undefined (reading 'blobfish')`)
- `goldEN_FISH` has the wrong ID and name capilatization
- it seems the `X` icon is gone when fish wasn't caught

**Comment by DuckySoLucky** [comment]
> So after testing it, I have a few things..
> 
> * `jjww2`'s profile doesn't load (`Cannot read properties of undefined (reading 'blobfish')`)
> * `goldEN_FISH` has the wrong ID and name capilatization
> * it seems the `X` icon is gone when fish wasn't caught

First two fixed

**Review by metalcupcake5 — APPROVED** [review]
lgtm, tested, `zeroing`'s profile does not load due to rift ferret

**Pull request merged**
