### PR TITLE
Fix #23

### LINKED ISSUE #23: Possible issue with username
**Describe the bug**
When a player username contains a underscore(I guess, I can give you the username for you to look into), the API will return `{"error":"TypeError: Cannot read property 'includes' of undefined"}`
However, the main page still shows the player data properly.

### PR DESCRIPTION
**Pull request by AnsonYeung**
I haven't run a test of this. But this should solve the issue #23

### CODE REVIEW

**Comment by metalcupcake5** [comment]
Please test this to make sure it works, thanks!

**Comment by AnsonYeung** [comment]
I can't set up the development environment to test this. I get error when trying to `npm i`.

**Comment by felix642** [comment]
I just tested it on my machine. It doesn't work

**Comment by metalcupcake5** [comment]
I'm gonna merge this into my test branch to double check things.

**Pull request merged**
