### PR TITLE
feat: add SkyBlock Levels

### LINKED ISSUE #1816: SkyBlock Levels Display?
> **Is your suggestion related to a problem? Please describe in detail.**

No

> **Describe your suggestion**

Allow users to see the skyblock level (as of 0.15 SkyBlock Update) progression/display above the player skills tab

> **Describe alternatives you've considered**
Ex. [...] could be a problem, but [...]

No?

> **Additional context**
Add any other context or screenshots about the suggestion here.

No?

### PR DESCRIPTION
**Pull request by DuckySoLucky**
## Description

Adds SkyBlocks Levels
Closes #1816

## Examples
image
image
image

### CODE REVIEW

**Comment by MattTheCuber** [comment]
Why is social there 2x and taming missing?

**Comment by MattTheCuber** [comment]
Hear me out:
You could make the progress bar out of the maximum SkyBlock level that way people can quickly compare their progress through the game. Idk, just an idea.

Could also color the bar or text somewhere to match the level prefix you get at specific Skyblock levels

**Comment by DuckySoLucky** [comment]
> Why is social there 2x and taming missing?

Because yes

**Comment by DuckySoLucky** [comment]
> Hear me out:
You could make the progress bar out of the maximum SkyBlock level that way people can quickly compare their progress through the game. Idk, just an idea.

8f9bwy3t

**Review by WarpWing — APPROVED** [review]

**Review by MartinNemi03 — APPROVED** [review]
lgtm, tested
image
in future, we could investigate how to automate the maximum possible level (once it causes too much pain to update), but it works for now, good job ducky 👍

**Comment by MattTheCuber** [comment]
Imagine hard coding values smh

**Pull request merged**
