### PR TITLE
fix: wrong MushroomCow Pet Data

### PR DESCRIPTION
**Pull request by DuckySoLucky**
Hypixel changed Mooshroom Cow stats, https://wiki.hypixel.net/Mooshroom_Cow_Pet

### CODE REVIEW

**Comment by dukio** [comment]
Wiki says 0.99 though?
image

**Comment by dukio** [comment]
@DuckySoLucky you sure it's 25% at lvl 100 uncommon? got any screens?

Wiki says it's the same as common
https://wiki.hypixel.net/Mooshroom_Cow_Pet#Uncommon_

So there should be nothing left to update in this PR (can be closed)

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky you sure it's 25% at lvl 100 uncommon? got any screens?
> 
> Wiki says it's the same as common https://wiki.hypixel.net/Mooshroom_Cow_Pet#Uncommon_
> 
> So there should be nothing left to update in this PR (can be closed)

image
From wiki, they have 20% and 25% which one is correct I'm not sure ;-;

**Comment by DuckySoLucky** [comment]
https://canary.discord.com/channels/738971489411399761/820755886262976553/1025136582652604456

**Pull request closed without merging**
