### PR TITLE
Change let to const when not re-assigned

### PR DESCRIPTION
**Pull request by Korase**
After doing this for pet-stats constants for dukio, I decided it would be a good fit to do it for every single file.

### CODE REVIEW

**Comment by dukio** [comment]
Will check this in a bit but... do you have a script or something to find these? or did you go through all fines manually 😅 ?

**Comment by Korase** [comment]
Manually 😅

**Review by dukio — APPROVED** [review]
quickly looked through the changes in github but also tested some profiles in localhost and it works fine so 👍

**Review by MartinNemi03 — APPROVED** [review]
LGTM!

**Pull request merged**
