### PR TITLE
refactor: getMinions and getMinionSlots optimization 

### PR DESCRIPTION
**Pull request by WarpWing**
Optimized getMinionSlotsremoving by unnecessary sorting of the MINION_SLOTS keys and used the Array.prototype.reduce method to count the number of unique minions efficiently. Also removed weird comparisons and index variable, replaced with indexOf().

### CODE REVIEW

**Comment by DuckySoLucky** [comment]
Front page where

**Comment by WarpWing** [comment]
> Front page where

We are not worthy and that makes me sadge. (I'll sneak it in with the next big optimization)

**Comment by MartinNemi03** [comment]
> > Front page where
> 
> We are not worthy and that makes me sadge. (I'll sneak it in with the next big optimization)

You know that I actually look into what changes are made?

**Comment by WarpWing** [comment]
> > > Front page where
> > 
> > 
> > We are not worthy and that makes me sadge. (I'll sneak it in with the next big optimization)
> 
> You know that I actually look into what changes are made?

Stop. Don't do that. Competency is overrated.

**Comment by WarpWing** [comment]
DO NOT MERGE THIS CODE BREAKS

**Pull request closed without merging**
