### PR TITLE
Small Easter Egg

### PR DESCRIPTION
**Pull request by jaideng1**
Small chance that the player's model will start rotating. This serves pretty much no purpose, but it is fun to see.

### CODE REVIEW

**Comment by nstringham** [comment]
I have a few reservations for this
1. people will probably just think its a bug
2. is it really worth the performance overhead for something that only happens one in a million times
3. shouldn't easter eggs be unlocked by doing something not just getting lucky

**Review by nstringham — CHANGES_REQUESTED** [review]
please don't inline non-critical js

**Review by nstringham — CHANGES_REQUESTED** [review]
please animate css with css animations not with javascript setInterval

**Comment by metalcupcake5** [comment]
>     3. shouldn't easter eggs be unlocked by doing something not just getting lucky

I've already added an easter egg that is randomized, so I dont have anything against that part.
I agree that it is unnecessary and a possible waste of a user's resources though

**Comment by nstringham** [comment]
>I've already added an easter egg that is randomized

@metalcupcake5 Really what?

**Comment by jaideng1** [comment]
> > I've already added an easter egg that is randomized
> 
> @metalcupcake5 Really? what?

I think it's the "snow monke" thing

**Comment by jaideng1** [comment]
I'm going to close this, due to it being unnecessary

**Pull request closed without merging**
