### PR TITLE
 Better theming

### PR DESCRIPTION
**Pull request by nstringham**
This PR adds a more robust theming system including support for light themes it also adds a Candycane theme to demonstrate the new light mode.
image

### CODE REVIEW

**Review by metalcupcake5 — APPROVED** [review]

**Comment by metalcupcake5** [comment]
I'm just gonna assume you've tested it :)

**Comment by nstringham** [comment]
> I'm just gonna assume you've tested it :)

yes I always test before I push

**Comment by nstringham** [comment]
Hey It's December it would be nice if we could merge this

**Comment by nstringham** [comment]
I'm closing this PR to convert it to sass I will reopen it against master when I'm done

**Pull request closed without merging**
